#!/bin/sh
# Called by "git commit" with no arguments.  

expectedEmail='zzandy@gmail.com'

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

email=$(git config --get user.email)

echo $against

if [ "$email" != "$expectedEmail" ]
then
	echo "Incorrect author email"
    echo "    expecting: $expectedEmail"
    echo "    got:       $email"
	exit 1 
fi
